### ISSUE TITLE
Plot historical trades on the map

### ISSUE THREAD

**Issue by Reigoro** [tradingpanel/TradingPanel#5]
Toggle button on/off to show historical trades on the chart.
Toggle on/off to show buy and sell price

![image](https://user-images.githubusercontent.com/62139344/76619125-72f65700-652a-11ea-90c1-86a19b953473.png)

**Comment by tradingpanel** [comment]
It will be done in March.

**Comment by tradingpanel** [comment]
I'm sorry, there was a lot of effort on the Futures, we'll add it to the plan in May.

**Comment by tradingpanel** [comment]
![image](https://user-images.githubusercontent.com/51719513/90759462-1ffaaa00-e2e9-11ea-8c09-90659309bcb0.png)
Done)

**Comment by krisj** [comment]
I cannot see any historical trades on charts. Do I have to turn them on somehow?

**Comment by tradingpanel** [comment]
> I cannot see any historical trades on charts. Do I have to turn them on somehow?

you need to click on a position for orders in it to appear, then marks of executed orders will appear on the chart

**Comment by krisj** [comment]
> > I cannot see any historical trades on charts. Do I have to turn them on somehow?
> 
> you need to click on a position for orders in it to appear, then marks of executed orders will appear on the chart

Does it only work on the trades that were placed by your app? I am also not seeing my historical orders/trades in the app - so I am assuming you don't pull the history from the exchange, only the finandy trades? Is that correct?

**Comment by krisj** [comment]
It would be really really useful if there was a way to display historical orders (without clicking on the positions) on the chart as well. Similar to what the MT5 (if you are familiar with it) platform does for example. Maybe that can be another enhancement to this feature...

**Comment by tradingpanel** [comment]
> It would be really really useful if there was a way to display historical orders (without clicking on the positions) on the chart as well. Similar to what the MT5 (if you are familiar with it) platform does for example. Maybe that can be another enhancement to this feature...

Let's make a separate button to display all orders executed, I think in October
