### ISSUE TITLE
New request: ...ХОТЕЛОСЬ БЫ ЧТОБЫ ОТОБРАЖАЛАСЬ НА ЭКРАНЕ ЛИНИЯ И ЦЕНА ВХОДА ГДЕ ВХОДИЛ В ПОЗИЦИЮ БЫЛО БЫ ОЧЕНЬ УДОБНО

### ISSUE THREAD

**Issue by OBMEN24-24** [tradingpanel/TradingPanel#6]
.ХОТЕЛОСЬ БЫ ЧТОБЫ ОТОБРАЖАЛАСЬ НА ЭКРАНЕ ЛИНИЯ И ЦЕНА ВХОДА ГДЕ ВХОДИЛ В ПОЗИЦИЮ БЫЛО БЫ ОЧЕНЬ УДОБНО Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tradingpanel** [comment]
в терминале показывается уровень цены безубытка позиции. Этого не достаточно? 
Или нужно отмечать где был исполнен ордер? Это мы добавим в августе.

**Comment by OBMEN24-24** [comment]
Спасибо

ср, 29 июл. 2020 г. в 07:39, Trading Panel <notifications@github.com>:

**Comment by tradingpanel** [comment]
Дубль задачи #5
